### PR TITLE
299 datetime.datetime timestamps tz aware

### LINKED ISSUE #299: timezone aware fixes?
would it be an idea to add the possibility of returning timezone aware datetime.datetime objects instead of datetime.time objects in the fix records?

in IGC files the time is recorded in UTC, leading to potentially weird situations when your are in a timezone far away from UTC. You can have fixes going over the date line, from `23:59` -> `00:00`

this recently lead to a problem in my program, trying to analyze glider flights for the gliding world championship in uvalde (UTC-5).

Adding this optional conversion would necessitate less conversions in downstream packages/programs. I see from the reader that it finds `utc_date` from one of the H records. ~Im not sure if this field is required in the format.~ [this source](https://xp-soaring.github.io/igc_file_format/igc_format_2008.html#link_2.1) says this record is required and always declared before the B records, so this would be possible without having to loop in a weird order.

Curious to hear how you look at this 😄

### PR DESCRIPTION
**Pull request by sylvainvdm**
Fixes #299

### CODE REVIEW

**Comment by bubeck** [comment]
Thanks for your PR. I am working on it now. I changed it to be Python 2/3.0 compatible. Also I decided to go for an additional key called "datetime" to store a datetime.datetime (including TZ=UTC) and "datetime_locale" with TZ from HFTZN to not break compatibiliy. I will make merge soon with 1-2 days.

**Comment by bubeck** [comment]
Your PR has been adopted and merged. Please let me know. Next step is skip_duplicate

**Comment by sylvainvdm** [comment]
> Thanks for your PR. I am working on it now. I changed it to be Python 2/3.0 compatible. Also I decided to go for an additional key called "datetime" to store a datetime.datetime (including TZ=UTC) and "datetime_local" with TZ from HFTZN to not break compatibiliy. I will make merge soon with 1-2 days.

Looks good! Agree that your implementation is preferred.

For next time, feel free to edit my branches. For me it feels nice to have my contributions showing up in the github repo :)

**Comment by bubeck** [comment]
Yes, I will. Looking forward for new contributions from you! :-)

**Pull request closed without merging**
